Replace fmt.Println with fmt.Printf for the constant newline-ending string weblistPageClosing.
google/pprof pull request #665
Opened 2021-11-03 22:48 UTC by zpavlinovic

This would otherwise be caught with the improved vet printf checker (https://github.com/golang/go/issues/30436).

2021-11-03 22:50 UTC, aalexand approved these changes

2021-11-04 02:59 UTC, aalexand requested changes
Could you elaborate why is this change needed? What's wrong with Println?

2021-11-04 03:05 UTC, aalexand commented
> Could you elaborate why is this change needed? What's wrong with Println?

If this is to avoid a redundant newline, then I think it's easier to update the value of the weblistPageClosing var to remove it there and leave the code as is.

And also the PR description needs to be updated I think. I don't think this change has anything to do with the linked 'go vet' changes. Those changes are about format strings for Printf.

2021-11-04 03:13 UTC, zpavlinovic commented
> > Could you elaborate why is this change needed? What's wrong with Println?
> 
> If this is to avoid a redundant newline, then I think it's easier to update the value of the weblistPageClosing var to remove it there and leave the code as is.

Sounds good.

> And also the PR description needs to be updated I think. I don't think this change has anything to do with the linked 'go vet' changes. Those changes are about format strings for Printf.

Yes, it is about avoiding a redundant new line. The reason I mentioned vet is because a previous [limitation](https://github.com/golang/go/issues/30436) has been recently addressed. I will change the description.

2021-11-04 03:20 UTC, aalexand commented
The description still mentions "go vet".

2021-11-04 03:24 UTC, zpavlinovic commented
> The description still mentions "go vet".

Hopefully, I have corrected it at all the relevant places now.

2021-11-04 04:01 UTC, aalexand approved these changes

2021-11-04 04:45 UTC, merged